---
sidebar: sidebar 
permalink: ONTAP/choose-ontap-910-later.html 
keywords: choose ontap target version, ontap update recommendations, identify ontap target version 
summary: ONTAP 스토리지 시스템을 업그레이드하기 전에 각 ONTAP 버전이 제공하는 이점과 위험에 대해 알아보십시오. 
---
= ONTAP 대상 버전 9.10 이상을 선택합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템에 사용할 ONTAP 버전을 선택하기 전에 먼저 이점을 파악하고 ONTAP 대상 버전과 관련된 위험을 이해하는 것이 중요합니다.

대상 버전을 선택하고 현재 버전과 비교하여 ONTAP에서 특정 버전으로 업데이트할 때의 이점을 이해할 수 있습니다. 또한 특정 버전의 ONTAP로 업데이트할 때 발생할 수 있는 위험 및 새로운 위험(있는 경우)도 확인할 수 있습니다.


NOTE: ONTAP 9.10 이상 버전을 실행하는 경우에만 이 기능을 사용할 수 있습니다.

.단계
. BlueXP  왼쪽 탐색 모음에서 * 상태 > 소프트웨어 업데이트 * 를 선택합니다.
+
소프트웨어 업데이트가 필요한 클러스터의 목록이 표시됩니다. 권장 대상 버전으로 업데이트하거나 다른 버전을 선택할 수 있습니다.



|===
| 만약... | 수행할 작업... 


 a| 
을(를) 권장 버전으로 업데이트하려는 경우
 a| 
. 대상 버전 * 열에서 * 버전 비교 * 를 클릭하여 권장되는 ONTAP 버전으로 업데이트할 때 얻을 수 있는 기능과 위험성을 확인하십시오.
. 해결할 위험, 계속 남아 있는 위험 및 업데이트 후에 발생할 새로운 위험에 대한 정보를 선택하고 확인합니다.
. 필요에 따라 * 업데이트 계획 다운로드 * 를 클릭하여 업데이트 계획 사본을 다운로드합니다.
. 업데이트 프로세스를 시작하려면 * 업데이트 시작 * 을 클릭합니다.




 a| 
다른 버전을 선택하려는 경우
 a| 
. 대상 버전 * 열에서 드롭다운을 클릭하고 * 다른 버전 선택 * 을 선택합니다.
. 기능의 이점과 위험 이점을 보려면 버전을 선택하십시오.
. 해결할 위험, 계속 남아 있는 위험 및 업데이트 후에 발생할 새로운 위험에 대한 정보를 선택하고 확인합니다.
. 필요에 따라 * 업데이트 계획 다운로드 * 를 클릭하여 업데이트 계획 사본을 다운로드합니다.
. 업데이트 프로세스를 시작하려면 * 업데이트 시작 * 을 클릭합니다.


|===