---
sidebar: sidebar 
permalink: ONTAP/fix-blockers-warnings.html 
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings 
summary: ONTAP 차단기를 수정하고 ONTAP 업데이트를 완료할 수 없는 경고를 확인합니다. 
---
= ONTAP 업그레이드 전에 BlueXP  소프트웨어 업데이트를 사용하여 모든 차단기를 수정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템의 ONTAP 대상 버전을 식별한 후에는 모든 차단기를 수정 및 확인하고 ONTAP 스토리지 시스템을 업데이트하기 전에 경고를 검토해야 합니다.

.필요한 BlueXP 역할:
조직 관리자, 폴더 또는 프로젝트 관리자, 저장소 관리자 또는 시스템 상태 전문가. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["BlueXP 액세스 역할에 대해 알아보세요."^]

모든 차단제를 수정하고 승인하는 것은 필수적이며 원활한 소프트웨어 업데이트 프로세스를 보장합니다.

.단계
. BlueXP  왼쪽 탐색 모음에서 * 상태 > 소프트웨어 업데이트 * 를 선택합니다.
+
소프트웨어 업데이트가 필요한 클러스터의 목록이 표시됩니다.

. 스토리지 시스템의 ONTAP 대상 버전을 확인합니다. ONTAP 대상 버전 식별에 대한 자세한 내용은 을 link:../ONTAP/choose-ontap-910-later.html["ONTAP 버전을 비교하여 BlueXP  소프트웨어 업데이트를 통한 이점과 위험을 이해합니다"]참조하십시오.
. ONTAP 대상 버전을 결정한 후 *업데이트 준비*를 선택하여 업데이트 프로세스를 시작합니다.
+
차단 및 경고 목록이 표시됩니다.

. 차단기를 선택하여 차단기를 수정하는 지침을 봅니다.
. 차단기를 해결하기 위해 제공된 단계를 수동으로 수행합니다.
. 수정된 차단 항목을 선택하고 *선택 항목 확인*을 선택하면 차단 항목이 수정되었음을 확인할 수 있습니다.



NOTE: 업데이트를 진행하려면 모든 차단기를 수정하고 확인해야 합니다.

. 소프트웨어 업데이트를 진행하기 전에 경고 내용을 검토하려면 *경고* 탭을 선택하세요.
. *확인* 탭을 선택하면 수정된 차단 사항을 볼 수 있습니다.
. 업데이트 과정을 계속하려면 *업데이트 계속*을 선택하세요.

